import type { NextPage } from "next";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import { ProductsContext } from "../../ProductsContext";
import styles from "../../styles/Home.module.css";

export default function Produtos() {
  const { data, count, increase } = useContext(ProductsContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Produtos</h1>
        {Object.entries(data).map((prod) => (
          <div className={styles.prod} key={prod[1].pdt_id}>
            <img
              // loader={myLoader}
              src={`https://localhost/sites/wc_aliancadistribuidora/uploads/${prod[1].pdt_cover}`}
              alt="Picture of the author"
              width={100}
              height={100}
            />

            <div>
              <h1>{prod[1].pdt_title}</h1>
              <p>{prod[1].pdt_content}</p>
              <input type="text" value={count} />
              <button onClick={increase}>Orçamento</button>
            </div>
          </div>
        ))}
      </main>
      <footer></footer>
    </div>
  );
}
