import type { GetServerSideProps } from "next";
import Head from "next/head";
import fetch from "node-fetch";
import https from "https";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import { ProductsContext } from "../ProductsContext";

export default function Home() {
  const { data } = useContext(ProductsContext);
  console.log(Object.entries(data));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Home </h1>
        {Object.entries(data).map((prod) => (
          <div className={styles.prod} key={prod[1].pdt_id}>
            <img
              // loader={myLoader}
              src={`https://localhost/sites/wc_aliancadistribuidora/uploads/${prod[1].pdt_cover}`}
              alt="Picture of the author"
              width={100}
              height={100}
            />

            <div>
              <h1>{prod[1].pdt_title}</h1>
              <p>{prod[1].pdt_content}</p>
              <button>Orçamento</button>
            </div>
          </div>
        ))}
      </main>
      <footer></footer>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps = async () => {

//   return {
//     props: {
//       datas,
//     },
//   };
// };
