import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { ProductsContext } from "../../ProductsContext";
import styles from "../../styles/Home.module.css";

const Produto: NextPage = () => {
  const data = useContext(ProductsContext);
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Produto</h1>
      </main>
      <footer></footer>
    </div>
  );
};

export default Produto;
